version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1 # Use the Ruby orb for simplified Ruby setup

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Check Ruby Version
          command: ruby -v
      - ruby/install-deps # Install dependencies, assumes a Gemfile and Gemfile.lock are present


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["3.0", "3.1", "3.3"]
